name: Create Release Note
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: 버전 정보 변수에 저장
        run: |
          echo "version=v$(echo '${{ github.head_ref }}' | tr -d 'release-')" >> $GITHUB_OUTPUT
        id: output_version
      - name: Create Release Note
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.output_version.outputs.version }}
          generateReleaseNotes: true
