# Generated by Django 3.2.19 on 2023-07-17 06:16

from django.db import migrations, models
import django.db.models.deletion
import restframework.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.CharField(max_length=10, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", restframework.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "mem_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("mem_name", models.CharField(max_length=10)),
                ("mem_number", models.IntegerField()),
                ("addr", models.CharField(max_length=2)),
                ("phone1", models.CharField(blank=True, max_length=3, null=True)),
                ("phone2", models.CharField(blank=True, max_length=8, null=True)),
                ("height", models.SmallIntegerField(blank=True, null=True)),
                ("debut_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Buy",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("prod_name", models.CharField(max_length=6, null=True)),
                ("group_name", models.CharField(blank=True, max_length=4, null=True)),
                ("price", models.IntegerField()),
                ("amount", models.SmallIntegerField()),
                (
                    "mem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="restframework.member",
                    ),
                ),
            ],
        ),
    ]
