# Generated by Django 3.2 on 2023-07-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('mem_name', models.CharField(max_length=10)),
                ('mem_number', models.IntegerField()),
                ('addr', models.CharField(max_length=2)),
                ('phone1', models.CharField(blank=True, max_length=3, null=True)),
                ('phone2', models.CharField(blank=True, max_length=8, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('debut_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=6, null=True)),
                ('group_name', models.CharField(blank=True, max_length=4, null=True)),
                ('price', models.IntegerField()),
                ('amount', models.SmallIntegerField()),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restframework.member')),
            ],
        ),
    ]
