# Generated by Django 3.2 on 2022-10-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='prod_name',
        ),
        migrations.AddField(
            model_name='buy',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='restframework.product'),
        ),
    ]
