# Generated by Django 3.2.19 on 2023-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restframework", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
