# Generated by Django 3.2 on 2022-10-01 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0002_auto_20221001_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='buy',
            name='prod',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='restframework.product'),
        ),
    ]
