# Generated by Django 3.2 on 2023-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0003_auto_20221001_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='prod',
        ),
        migrations.AddField(
            model_name='buy',
            name='prod_name',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='buy',
            table='buy',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
