name: Release Create
on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
        - name: Create Release Note
          if: startsWith(github.ref_name, 'main')
          uses: ./.github/actions/release-note
