name: Create Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: 버전 정보 변수에 저장 (릴리즈)
        if: ${{ startsWith(github.head_ref, 'release') }}
        run: |
          echo "version=v$(echo '${{ github.head_ref }}' | cut -d '-' -f2)" >> $GITHUB_ENV
      - name: 태그 정보 확인
        run: |
          echo "$GITHUB_REF"
          if [ "$GITHUB_REF" == refs/tags/* ]; then
            echo "version=v$(echo '$GITHUB_REF' | sed 's|refs/tags/||')" >> $GITHUB_ENV
          fi
          echo $version
      - name: 버전 정보 변수에 저장 (핫픽스)
        if: ${{ startsWith(github.head_ref, 'HOTFIX') }}
        run: |
          version=v$(echo '${{ github.head_ref }}' | cut -d '-' -f2)
          major_minor=${version:0:-1}
          patch=${version:(-1):1}
          patch=`expr $patch + 1`
          version=$major_minor$patch
          echo "version=$version" >> $GITHUB_ENV
      - name: 릴리즈 노트 생성
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.version }}
          generateReleaseNotes: true
