name: Create Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: 버전 정보 변수에 저장
        run: |
          echo "version=v$(echo '${{ github.head_ref }}' | cut -d '-' -f2)" >> $GITHUB_OUTPUT
        id: output_version
      - name: 릴리즈 노트 생성
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.output_version.outputs.version }}
          generateReleaseNotes: true
