name: Release Create
on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: extract version from branch name
        run: |
          # 브랜치 이름 추출
          VERSION="v$(echo '${{ github.head_ref }}' | tr -d 'release-')"
          echo "VERSION: $VERSION" 
      - name: set output
        run: |
          echo "version='$VERSION'" >> $GITHUB_ENV
      - name: Create Release Note
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.version }}
          generateReleaseNotes: true
