name: Release Create
on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 브랜치에서 버전 이름 가져오기
        run: |
          # 브랜치 이름 추출
          VERSION="v$(echo '${{ github.head_ref }}' | tr -d 'release-')"
      - name: 버전 정보 변수에 저장
        run: |
          echo "$VERSION 버전 릴리즈 생성"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        id: output_version
      - name: Create Release Note
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.output_version.outputs.version }}
          generateReleaseNotes: true
