name: Release Create
on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  create_release_note:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Create Release Note
          if: startsWith(github.ref_name, 'main') && contains(github.head_ref, 'release')
          uses: ./.github/actions/release-note
